version: '3.8'

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    image: postgres:14.5-alpine3.16

  backend:
    container_name: asp_backend
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=root
      - DB_NAME=postgres
    depends_on:
      - db


  client:
    container_name: client
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5001:3000"

  proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

    
  